image: node:lts

stages:
  - test
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/

test-backend:
  stage: test
  script:
    - cd backend
    - npm ci --cache .npm --prefer-offline
    - npm run test

lint-backend:
  stage: test
  script:
    - cd backend
    - npm ci --cache .npm --prefer-offline
    - npm run lint

build-backend:
  stage: build
  script:
    - cd backend
    - npm ci --cache .npm --prefer-offline --omit=dev
    - npm run build
    - cp -r node_modules ./dist
    - cp healthcheck.js ./dist
  artifacts:
    name: "Backend Build"
    paths:
      - backend/dist

#test-frontend:
#  stage: test
#  image: cypress/base:18.12.0
#  variables:
#    ELECTRON_EXTRA_LAUNCH_ARGS: "--headless --disable-gpu --disable-software-rasterizer --no-sandbox"
#  script:
#    - cd frontend
#    - npm ci --cache .npm --prefer-offline
#    - npm run config:defaults:mempool.cash
#    - npm run cypress:run

lint-frontend:
  stage: test
  script:
    - cd frontend
    - npm ci --cache .npm --prefer-offline
    - npm run config:defaults:mempool.cash
    - npm run lint

test-build-frontend:
  stage: build
  image: danger89/node:lts-rsync
  rules:
    - if: '$CI_PROJECT_NAMESPACE == "bitcoincash" && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'
  script:
    - cd frontend
    - npm ci --cache .npm --prefer-offline --omit=dev
    - npm run config:defaults:mempool.cash
    - npm run build

deploy-docker-backend:
  stage: deploy
  rules:
    - if: '$CI_PROJECT_NAMESPACE == "bitcoincash" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  tags:
    - shell
  before_script:
    - echo "${DOCKER_PASSWORD}" | docker login -u danger89 --password-stdin
  script:
    - docker build -t danger89/bch-explorer-backend -f backend/DockerfileBCH --build-arg commitHash="$CI_COMMIT_SHORT_SHA" ./backend/
    - docker push danger89/bch-explorer-backend
  after_script:
    - docker logout

build-and-deploy-frontend:
  stage: build
  image: danger89/node:lts-rsync
  rules:
    - if: '$CI_PROJECT_NAMESPACE == "bitcoincash" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  script:
    - cd frontend
    - npm ci --cache .npm --prefer-offline --omit=dev
    - npm run config:defaults:mempool.cash
    - npm run build
  environment:
    name: production
    url: https://explorer.melroy.org
  artifacts:
    name: "Frontend Build"
    expire_in: 3 months
    paths:
      - frontend/dist/mempool/browser
