image: node:lts

stages:
  - test
  - build

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/

build-frontend:
  stage: build
  image: danger89/node:lts-rsync
  script:
    - cd frontend
    - npm ci --cache .npm --prefer-offline
    - npm run config:defaults:mempool.cash
    - npm run build
  artifacts:
    name: "Build"
    paths:
      - frontend/dist/mempool/browser

#test-frontend:
#  stage: test
#  image: cypress/base:18.12.0
#  variables:
#    ELECTRON_EXTRA_LAUNCH_ARGS: "--headless --disable-gpu --disable-software-rasterizer --no-sandbox"
#  script:
#    - cd frontend
#    - npm ci --cache .npm --prefer-offline
#    - npm run config:defaults:mempool.cash
#    - npm run cypress:run

lint-frontend:
  stage: test
  script:
    - cd frontend
    - npm ci --cache .npm --prefer-offline
    - npm run config:defaults:mempool.cash
    - npm run lint
